# Generated by Django 5.1.2 on 2024-10-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='peerone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_peer1', models.IntegerField()),
                ('name_peer1', models.CharField(max_length=100)),
                ('event_date_peer1', models.DateTimeField()),
            ],
        ),
    ]
