# Generated by Django 5.1.2 on 2024-10-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_creativereser_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativereser',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creativereser',
            name='event_date',
            field=models.DateField(),
        ),
    ]
